language: rust
dist: bionic

env:
  global:
    - HOST=x86_64-unknown-linux-gnu

jobs:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

    # Static checks
    - name: "LoC and style tests"
      before_script: rustup component add rustfmt clippy
      script:
        - cargo test --test loc
        - cargo fmt -- --check
        - cargo clippy --all-targets -- -D warnings
    - name: "Dependency Audit"
      install: cargo install cargo-audit
      script: cargo audit
      cache: cargo

  allow_failures:
    - rust: nightly
  fast_finish: true

before_install: ci/before_install.sh

cache: false

install: cargo build --target "${TARGET:-$HOST}" --verbose

script: skip
