[package]
name = "kibi"
version = "0.1.1"
authors = ["Ilaï Deutel"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "A text editor in less than 1024 lines of code with syntax higlighting, search and more."
repository = "https://github.com/ilai-deutel/kibi"
readme = "README.md"
keywords = ["editor", "terminal", "text-editor"]
categories = ["text-editors", "development-tools"]
exclude = [".gitignore", "rustfmt.toml", "syntax"]

[dependencies]
libc = "0.2.66"
nix = "0.17.0"
signal-hook = "0.1.13"

[dev-dependencies]
tokei = "10.1.1"

[badges]
travis-ci = { repository = "ilai-deutel/kibi", branch = "master" }
maintenance = { status = "actively-developed" }
